export * from './MainPage/MainPage'
export * from './AboutPage/AboutPage'
export * from './CartPage/CartPage'
export * from './CatalogPage/CatalogPage'
export * from './ContactsPage/ContactsPage'
export * from './FavoritePage/FavoritePage'
export * from './LoginPage/LoginPage'
export * from './RegisterPage/RegisterPage'